# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산속도가 빠르다

In [1]:
import numpy as np

## 2-1. np.array() 함수로 생성하기


### 1차원 배열 생성하기

In [9]:
# 1차원 배열 생성하기
arr = np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [6]:
#type 확인
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# array 함수에는 data에 1개만 들어가야 함
fadfa

In [ ]:
#데이터 타입 확인
for i in arr :
    type(i)
arr.dtype

In [23]:
#overflow 테스트
arr = np.array([2147483647,2,3,2147483647])
print(arr.dtype)
arr = np.array([2147483647,2,3,2147483647 + 2147483647],dtype=np.int64)
arr.dtype

int32


dtype('int64')

In [27]:
arr = np.array([1,2,3,4],dtype = float)
arr

array([1., 2., 3., 4.])

In [28]:
arr.dtype

dtype('float64')

In [30]:
# shape : 배열의 size
arr.shape

(4,)

In [32]:
# size : 배열 전체의 요소의 개수
arr.size

4

In [33]:
#ndim : 차원의 수
arr.ndim


1

In [37]:
#ndarray에는 같은 데이터 타입만 들어가야함
arr= np.array([1,2,3,3.14])
arr.dtype
arr

array([1.  , 2.  , 3.  , 3.14])

In [47]:
#int,float,string - > string
# >(big-endian),<(little-endian)
arr = np.array([1,2,3,'c',3.14,"123456789011234"])

arr.dtype
arr

array(['1', '2', '3', 'c', '3.14', '123456789011234'], dtype='<U15')

In [36]:
arr

array(['1', '2', '3', 'c'], dtype='<U11')

In [39]:
arr = np.array([1,2,3,3.14],dtype=int)
arr.dtype
arr

array([1, 2, 3, 3])

In [49]:
#ndarray에는 같은 데이터 타입만 들어가야함
arr= np.array([1,2,3,3.14])
arr.dtype
arr

array([1.  , 2.  , 3.  , 3.14])

In [50]:
# 기존의 배열을 이용하여 타입이 다른 배열을 생성하기
new_arr = arr.astype(float)
new_arr

array([1.  , 2.  , 3.  , 3.14])

In [51]:
arr.dtype,new_arr.dtype

(dtype('float64'), dtype('float64'))

## 2-9 NumPy 배열 Save & Load

In [4]:
arr = np.arange(0,5) # 0~4
arr

array([0, 1, 2, 3, 4])

In [7]:
np.save('my_arr',arr)


In [11]:
new_arr=np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])