# 3.연산

## 3-1. 산술연산

In [1]:
import numpy as np

In [4]:
# 1차원 배열
a = np.arange(1,5)
b = np.arange(5,9)

In [5]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [7]:
a + b

array([ 6,  8, 10, 12])

In [8]:
a - b

array([-4, -4, -4, -4])

In [9]:
a * b

array([ 5, 12, 21, 32])

In [10]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [19]:
# 2차원 배열
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

In [20]:
 a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [21]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [22]:
a * b
#단순곱셈(이렇게는 안쓰임)

array([[ 7, 16, 27],
       [40, 55, 72]])

### 행렬의 곱셈 (dot product)

In [23]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [25]:
b = b.reshape(3,2);
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [26]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [30]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [31]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## 배열과 숫자와의 연산

In [33]:
a = np.arange(1,4)

In [34]:
a + 3

array([4, 5, 6])

In [35]:
a - 3

array([-2, -1,  0])

# 3-2. Aggregaion 함수

## 1차원 배열

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
#max 값 찾기
a.max()

5

In [5]:
#min 값 찾기
a.min()

1

In [6]:
np.max(a),np.min(a)

(5, 1)

In [7]:
#sum값구하기
np.sum(a)

15

In [9]:
#평균 값 구하기
np.mean(a)

3.0

In [12]:
#이상치가 있는 경우 평균값은 배열의 데이터를 잘 대표하지 못한다.
b= np.array([1,2,3,4,100]) # 이상치(outlier)

In [14]:
#중앙값,중위값(median)
np.median(b)

3.0

In [15]:
#데이터가 짝수 개인 경우
b = np.array([1,3,5,100])
np.median(b)

4.0

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
np.std(a)

1.4142135623730951

### 2차원 배열

In [20]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.max(a),a.max()

(6, 6)

In [24]:
np.min(a),a.min()

(1, 1)

In [29]:
#2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a,axis=0) # 행

array([4, 5, 6])

In [30]:
np.max(a,axis=1) # 열

array([3, 6])

In [31]:
np.min(a,axis=0)

array([1, 2, 3])

In [32]:
np.min(a,axis=1)

array([1, 4])

In [33]:
np.sum(a,axis=0)

array([5, 7, 9])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

## 비교(comparison)

In [35]:
a = np.arange(1,6);

In [36]:
a>=3

array([False, False,  True,  True,  True])

In [37]:
a+3

array([4, 5, 6, 7, 8])

In [38]:
a==3

array([False, False,  True, False, False])

In [5]:
a = np.arange(1,5).cumsum()
a

array([ 1,  3,  6, 10], dtype=int32)

In [7]:
b = np.arange(1,10).reshape(3,3).cumsum(axis=1)
b

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [8]:
b = np.arange(1,7).reshape(2,3).cumsum(axis=1)
b

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [9]:
# corrcoef(상관계수)
# 키와 몸무게의 상관관계
h = [160,165,170,180]
w = [47,55,70,85]
np.corrcoef(h,w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [10]:
ha = np.mean(h)
wa = np.mean(w)
ha,wa

(168.75, 64.25)

In [11]:
a=np.sqrt(np.sum((h - ha)**2))
a

14.79019945774904

In [12]:
b=np.sqrt(np.sum((w - wa)**2))
b

29.098969053902923

In [13]:
c=np.sum((h - ha) * (w - wa))
c

426.25

In [14]:
r=c/(a*b)
r

0.990404850180661

## element wise(모든 원소에 대해 적용) 