# 5. 인덱싱과 슬라이싱

## 5-1.인덱싱

In [2]:
import numpy as np

In [3]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0],arr[4],arr[9],arr[-1]

(0, 4, 9, 10)

In [8]:
#a[-10] = *(a - 10)

In [10]:
arr2=np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr2[0][1],arr2[1][2],arr2[2][3]

(2, 7, 12)

In [15]:
arr2[0,1],arr2[1,2],arr2[2,3] # 다차원 인덱싱 기능 제공

(2, 7, 12)

In [16]:
arr2[-1][-2]

11

## 5-2. 슬라이싱

### 1차원 배열

In [20]:
# 3~끝까지 슬라이싱([start:end:step])
arr=np.arange(1,11)

In [22]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[2:5]

array([3, 4, 5])

In [24]:
arr[:5]

array([1, 2, 3, 4, 5])

In [25]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr=arr[:5]
new_arr[0] = 100
arr
# 영향을 미침 ㅇㅇ

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [6]:
copy_arr=np.copy(arr)
copy_arr[0] = 100
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###  2차원 배열

In [7]:
arr2=np.arange(1,13).reshape(3,4)

In [11]:
#첫번재 행을 모두 가져오기
copy_arr=arr2[0, :]# == copy_arr=arr2[0]
copy_arr

array([1, 2, 3, 4])

In [13]:
#세번째 열을 모두 가져오기
copy_arr= arr2[:,2]
copy_arr

array([ 3,  7, 11])

In [15]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# 첫번째,두번재 행을 모두 가져오기
copy_arr = arr2[:2,:]
copy_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# 두번째,세번째 열을 모두 가져오기
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [23]:
#[2,3]
#[6,7] 가져오기
arr2[:2,1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [26]:
# 1차원 배열
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# 1,3,5로 된 배열을 만들기
arr[0:5:2]

array([1, 3, 5])

In [29]:
# Fancy 인덱싱 (인덱스로 된 배열로 추출)
arr[[0,2,4]]

array([1, 3, 5])

In [30]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [34]:
arr2[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [35]:
#슬라이싱
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [4]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [37]:
cond = [False,True,False,False,True]
arr[cond]# 개수가 일치해야함.

array([1, 4])

In [39]:
cond = arr>2
arr[cond]
type(cond)

numpy.ndarray

In [44]:
# 짝수만 뽑기
arr[arr%2 == 0]

array([0, 2, 4])

In [19]:
# 짝수만 뽑기
cond = (arr < 1) | (arr > 2)
arr[cond]

array([0, 3, 4])

In [16]:
arr[(arr < 1) | (arr > 3)]

array([0, 4])